"""create tables

Revision ID: d01c007396b6
Revises: 
Create Date: 2024-07-14 04:55:11.992142

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d01c007396b6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "client",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("surname", sa.String(length=30), nullable=False),
        sa.Column("credit_card", sa.String(length=50), nullable=False),
        sa.Column("car_number", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client")),
        sa.UniqueConstraint("name", "surname", name=op.f("uq_client_name")),
    )
    op.create_table(
        "parking",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=100), nullable=False),
        sa.Column("opened", sa.Boolean(), nullable=False),
        sa.Column("count_places", sa.Integer(), nullable=False),
        sa.Column("count_available_places", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parking")),
    )
    op.create_table(
        "client_parking",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("parking_id", sa.Integer(), nullable=False),
        sa.Column("time_in", sa.DateTime(), nullable=False),
        sa.Column("time_out", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
            name=op.f("fk_client_parking_client_id_client"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parking_id"],
            ["parking.id"],
            name=op.f("fk_client_parking_parking_id_parking"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client_parking")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("client_parking")
    op.drop_table("parking")
    op.drop_table("client")
    # ### end Alembic commands ###
